version: "3"

services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    image: app/frontend
    restart: always
    # environment:
    #   - NODE_ENV=development
    #   - CHOKIDAR_USEPOLLING=true
    ports:
      - "80:80"
    volumes:
      - ./log:/var/log/nginx
    stdin_open: true
    tty: true
