FROM node:latest

# 작업 디렉토리 설정
RUN mkdir /srv/frontend

#ADD app /srv/frontend

WORKDIR /srv/frontend

ENV PATH /srv/frontend/node_modules/.bin:$PATH

COPY app/package.json /srv/frontend/package.json
COPY app/yarn.lock /srv/frontend/yarn.lock

#COPY app/package.json yarn.lock ./

# package install
RUN yarn install

# project build
#RUN yarn build

COPY app /frontend

#EXPOSE 3000
CMD ["yarn", "start"]